services:
  manager:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - interx-manager
    volumes:
      - "./:/srv"

networks:
  interx-manager:
    name: interx_default
    external: true
