services:
  manager:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - interx-manager
    volumes:
      - "./config.yml:/srv/config.yml"

networks:
  interx-manager:
    name: interx_default
    external: true
